api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core-sdk"
  name = ".NET SDK Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "0cc055d0ba9c682e289bab4b7bcd36547c8b93dd386fbf85ba66d6506290fe34"
    source = "https://github.com/dotnet/cli"
    source_sha256 = "aadb25e72977ba2e67ad785599c0ef8af98a1e27675483c1dd986f446e3547d7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.505.linux-amd64-cflinuxfs3-0cc055d0.tar.xz"
    version = "2.1.505"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "fddaed90c7adde9e023ff615891313ebafe1d4e66ff047438b65071eab9f5645"
    source = "https://github.com/dotnet/cli"
    source_sha256 = "f720a5486f7370551afebd926b6dfae676714687b30b5e5826eb5e486101fda0"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.506.linux-amd64-cflinuxfs3-fddaed90.tar.xz"
    version = "2.1.506"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "cab256af9a28bd7395f95d245fdb4dd15b4d56156afe9695a79ff10dfbf5be80"
    source = "https://github.com/dotnet/cli/archive/243f6de49b3c4c16dd1a6413c39f463fcbdcf58d.tar.gz"
    source_sha256 = "47e87c339c0069b6f487fa7077d7db41eff18d9334b1753d885d6568062b45cc"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.701.linux-amd64-cflinuxfs3-cab256af.tar.xz"
    version = "2.1.701"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "21163765b26dc04eb6384ff92a63508d87ec64cc08640a893458dcb8d62f5b73"
    source = "https://github.com/dotnet/cli/archive/71d02fc7fa0590da304249427033298ceea97307.tar.gz"
    source_sha256 = "a03a740a0a178d1973de78cdb286871874e622eb0b3057e8163fa067a94f8511"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.802.linux-amd64-cflinuxfs3-21163765.tar.xz"
    version = "2.1.802"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "de0126dd771e88b2275a5358c40e944c6d90ecc78255015539f35a838ea77fbe"
    source = "https://github.com/dotnet/cli"
    source_sha256 = "deade20a1e2bc07f168272f31b9a8867dc4c395f95f7e0541441a30eef716dba"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.104.linux-amd64-cflinuxfs3-de0126dd.tar.xz"
    version = "2.2.104"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "dbaee1297f86f874c50d4f09f3bda2fb83bb9825d782e5938a48b0f554ef4ea0"
    source = "https://github.com/dotnet/cli"
    source_sha256 = "cbc735430c4b93e367b448b4f3ebafd0a34b2cf48912e3b0bc40eb6a79539b38"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.106.linux-amd64-cflinuxfs3-dbaee129.tar.xz"
    version = "2.2.106"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "01c20c0601929e2f5112759fbecdb2eb2fb2000539e85532bff99aab9b51c819"
    source = "https://github.com/dotnet/cli"
    source_sha256 = "02656e78a7c4b2a92566848bf31f84ccfa2ed8bc8f09f9ff31563a7c845c58a7"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.107.linux-amd64-cflinuxfs3-01c20c06.tar.xz"
    version = "2.2.107"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "3278b7aa50428c5b834c87505c6ad963d4c58a8602f023d167997290c6ee4dab"
    source = "https://github.com/dotnet/cli"
    source_sha256 = "c32065086aa7f5101f68d0a2b82aef9392c7ca1360f0d1519060fbc8fc88f59e"
    stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.204.linux-amd64-cflinuxfs3-3278b7aa.tar.xz"
    version = "2.2.204"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "3cb2a1288f2aec913771391b441a7b17b256a445f60cc38cdb4eea0367d23779"
    source = "https://github.com/dotnet/cli/archive/3e0e612cb176daae0fce6ca54608d40428c9d27e.tar.gz"
    source_sha256 = "e7a0d34b933d2dcac5d7536ab850f75af967b52567c82cd75e36e7d8145c9c2e"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.301.linux-amd64-cflinuxfs3-3cb2a128.tar.xz"
    version = "2.2.301"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "4fb1b0c17777fba8a9decd019caf3b86cb141f26b4eb625d73de46e2471a0364"
    source = "https://github.com/dotnet/cli/archive/9f70fab4d2ab026c15d247ca228232c956b309e2.tar.gz"
    source_sha256 = "8db9f1acfc0820043f097aef33f46aa065bd66384a6778327d09536a3acf9cc6"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.402.linux-amd64-cflinuxfs3-4fb1b0c1.tar.xz"
    version = "2.2.402"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "3aa0c6942f2a32e27e28733670051f0ef883767c0a8b7d34e03c6e9064333873"
    source = "https://download.visualstudio.microsoft.com/download/pr/886b4a4c-30af-454b-8bec-81c72b7b4e1f/d1a0c8de9abb36d8535363ede4a15de6/dotnet-sdk-3.0.100-linux-x64.tar.gz"
    source_sha256 = "12098fe29d5c857fd6093b1fd63eda9f91b92798e3748fcedc0e0727f1ac01c2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.0.100.linux-amd64-cflinuxfs3-3aa0c694.tar.xz"
    version = "3.0.100"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.12"
    sdks = ["2.1.801", "2.1.701", "2.1.605", "2.1.508"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.13"
    sdks = ["2.1.802", "2.1.606", "2.1.509"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.2.6"
    sdks = ["2.2.401", "2.2.205", "2.2.108"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.2.7"
    sdks = ["2.2.402", "2.2.301", "2.2.206", "2.2.109"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.0.0"
    sdks = ["3.0.100"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
