api = "0.2"

[buildpack]
id = "org.cloudfoundry.dotnet-core-sdk"
name = ".NET SDK Buildpack"
version = "{{ .Version }}"

[metadata]
include_files = ["bin/build","bin/detect","buildpack.toml","go.mod","go.sum"]
pre_package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "b27fef3583c867fb3965ea2bc04e13f8d8c1be3841603003f9171e333d43ce32"
source = "https://github.com/dotnet/cli/archive/7fa21d645bdafd6ee98ad5aaef92e3b359008139.tar.gz"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.402.linux-amd64-cflinuxfs3-b27fef35.tar.xz"
version = "2.1.402"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "553a32a49a46ca21b86789dd9f9c81917eae0485538f5d510be9eef2cf4e0c7c"
source = "https://github.com/dotnet/cli/archive/436c9d483c971aca295013a966301df7e4e6cc1e.tar.gz"
source_sha256 = "c4eadc8f92ec21c18c223b88183b796dd9a53a0bc2a754ac2cf16262db4baf32"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.403.linux-amd64-cflinuxfs3-553a32a4.tar.xz"
version = "2.1.403"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "aca24d1072c01af2feaabbd6b99e23663cbf6835ad8415d9413707d0926b4aed"
source = "https://github.com/dotnet/cli/archive/734cb0ccec2d606814d88e254712071ebb7caed7.tar.gz"
source_sha256 = "15766556ac96aea180caa5e513bf013b7ceea5dd3ce122928cff922a1ad031a1"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.503.linux-amd64-cflinuxfs3-aca24d10.tar.xz"
version = "2.1.503"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "e9c7179dd5b8311458bde41e554898b0df261ca3fde230f1e64289cb1076de90"
source = "https://github.com/dotnet/cli/archive/9b0b46aacc95a4e12fa7df23aa2c19dec1dacc03.tar.gz"
source_sha256 = "ecedcefdf5d8090e83c4f150ea2fa802f5dd92a2c3e1bb23b82a69fe1a9c9f18"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.509.linux-amd64-cflinuxfs3-e9c7179d.tar.xz"
version = "2.1.509"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "9157ae93a543b88168d913c97240bf602ffb525170c478414df19bec63a8b51b"
source = "https://github.com/dotnet/cli/archive/c81e08b11d740793f196d8c6b2f1e90557f7c367.tar.gz"
source_sha256 = "43baf353e8de58687f29b0d5f107c1803855a316e3062459d1ee1c647074dcf9"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.606.linux-amd64-cflinuxfs3-9157ae93.tar.xz"
version = "2.1.606"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "cab256af9a28bd7395f95d245fdb4dd15b4d56156afe9695a79ff10dfbf5be80"
source = "https://github.com/dotnet/cli/archive/243f6de49b3c4c16dd1a6413c39f463fcbdcf58d.tar.gz"
source_sha256 = "47e87c339c0069b6f487fa7077d7db41eff18d9334b1753d885d6568062b45cc"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.701.linux-amd64-cflinuxfs3-cab256af.tar.xz"
version = "2.1.701"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "21163765b26dc04eb6384ff92a63508d87ec64cc08640a893458dcb8d62f5b73"
source = "https://github.com/dotnet/cli/archive/71d02fc7fa0590da304249427033298ceea97307.tar.gz"
source_sha256 = "a03a740a0a178d1973de78cdb286871874e622eb0b3057e8163fa067a94f8511"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.802.linux-amd64-cflinuxfs3-21163765.tar.xz"
version = "2.1.802"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "94343f2e4fdb57298a08937e7d77bb82d5b0529b0d2fac4cdf4b6f19c1247dc5"
source = "https://github.com/dotnet/cli/archive/51868761f2d5506b64166cf787ef2d25217d675c.tar.gz"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.100.linux-amd64-cflinuxfs3-94343f2e.tar.xz"
version = "2.2.100"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "9a361e3cec9c424569eeec73742872af28dc484e9854277cd0f0feea80262449"
source = "https://github.com/dotnet/cli/archive/7a42b83262bb2b52804a2c14b4fad289d794c8be.tar.gz"
source_sha256 = "0b4a86f13d63418636762a997ecac5acd5ce5a8d59ff28f8a0f3e7a0c701ff4e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.109.linux-amd64-cflinuxfs3-9a361e3c.tar.xz"
version = "2.2.109"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "7131556f4eeec88f0ec7643986bd1ff72a9991d6e54cd1dafb650f32286a374b"
source = "https://github.com/dotnet/cli/archive/e12afeea4f3fafe462b8db2fe8ef5a28c0fbcd8b.tar.gz"
source_sha256 = "7dd2b7332533457255afe1e95ad7756a822ee9638a5ca441fd6d0338c4fff544"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.203.linux-amd64-cflinuxfs3-7131556f.tar.xz"
version = "2.2.203"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "1bd926b3a77e3a0cd809cb926de169a7d30f611a5814dae470feb3662443726d"
source = "https://github.com/dotnet/cli/archive/bee4faf6c3b7cdb784056d54e57083a5e334ce9d.tar.gz"
source_sha256 = "285ce5071de336e03b8d75414b35f39477697a9a1c12b393c14fb5ac2d64c70e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.206.linux-amd64-cflinuxfs3-1bd926b3.tar.xz"
version = "2.2.206"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "3cb2a1288f2aec913771391b441a7b17b256a445f60cc38cdb4eea0367d23779"
source = "https://github.com/dotnet/cli/archive/3e0e612cb176daae0fce6ca54608d40428c9d27e.tar.gz"
source_sha256 = "e7a0d34b933d2dcac5d7536ab850f75af967b52567c82cd75e36e7d8145c9c2e"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.301.linux-amd64-cflinuxfs3-3cb2a128.tar.xz"
version = "2.2.301"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "838ab023ed36b93463edd59f0f3dcfc2217888734d2bba8aa985ba1a54a800a9"
source = "https://github.com/dotnet/cli/archive/729b316c13bf9289b033272c07c7dfd046ffbcaf.tar.gz"
source_sha256 = "1e2463cc161ae8f516aa047b09bef29aff6732f8346626b312b3acd75e9191ba"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.401.linux-amd64-cflinuxfs3-838ab023.tar.xz"
version = "2.2.401"

[[metadata.dependencies]]
id = "dotnet-sdk"
sha256 = "4fb1b0c17777fba8a9decd019caf3b86cb141f26b4eb625d73de46e2471a0364"
source = "https://github.com/dotnet/cli/archive/9f70fab4d2ab026c15d247ca228232c956b309e2.tar.gz"
source_sha256 = "8db9f1acfc0820043f097aef33f46aa065bd66384a6778327d09536a3acf9cc6"
stacks = ["org.cloudfoundry.stacks.cflinuxfs3"]
uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.2.402.linux-amd64-cflinuxfs3-4fb1b0c1.tar.xz"
version = "2.2.402"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
