api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core-sdk"
  name = ".NET SDK Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "761e82b26e016bc45bf8c90a122b2342f0ec55313e449d1766aa6f16cb4679d3"
    source = "https://download.visualstudio.microsoft.com/download/pr/701502b0-f9a2-464f-9832-4e6ca3126a2a/62655f151db917025e9be8cc4b7c1ed9/dotnet-sdk-2.1.803-linux-x64.tar.gz"
    source_sha256 = "fcb46a4a0c99bf82b591bca2cd276e2d73b65e199f0d14c9cc48dcdf5fb2ffb0"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.803.linux-amd64-any-stack-761e82b2.tar.xz"
    version = "2.1.803"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "4c347c269189d3f6ff7321e505a4667f8c5fac2fcfb08a1d29f1f38d712f60c6"
    source = "https://download.visualstudio.microsoft.com/download/pr/9ba4d9b0-3fca-40ed-b5a2-1552dfa4f89e/8e5e555b543a7afd8fd764e080d25671/dotnet-sdk-2.1.804-linux-x64.tar.gz"
    source_sha256 = "51ce9fe209ed1ba5b077021fd23694808291ff8cf90dc56f04912b8cab9cb510"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.804.linux-amd64-any-stack-4c347c26.tar.xz"
    version = "2.1.804"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "d5cc7a66b0f3b9339453d2bbfb90fa0ef89dc8a2c7642668f5b0ae9a8d2e7d94"
    source = "https://download.visualstudio.microsoft.com/download/pr/4f51cfd8-311d-43fe-a887-c80b40358cfd/440d10dc2091b8d0f1a12b7124034e49/dotnet-sdk-3.0.101-linux-x64.tar.gz"
    source_sha256 = "08a2c0c985354daa527fe9cf0a726b1d1014dc74f40f0bc0f989afc1dbd97cae"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.0.101.linux-amd64-any-stack-d5cc7a66.tar.xz"
    version = "3.0.101"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "2896400a3392f473d8e28a98cd528e24544603fcc14800c8e167f9876b81cb01"
    source = "https://download.visualstudio.microsoft.com/download/pr/2e2cbde1-f97b-4d6f-8fd9-7880aa46b025/8e5ead3dda8340867ba1e09273993351/dotnet-sdk-3.0.102-linux-x64.tar.gz"
    source_sha256 = "c480d891bda841a27c4a70e04c8968da92220bcbbd32b709a9a3c5e90457eb5b"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.0.102.linux-amd64-any-stack-2896400a.tar.xz"
    version = "3.0.102"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "b19ff5e173b066b3f49626dffad56034bf232a7ba0d6e114a1a9badec904d202"
    source = "https://download.visualstudio.microsoft.com/download/pr/43f3a3bd-3df2-41e6-beca-3ec4952ca6c4/30fe7779249607d1bb3bb4b20d61a479/dotnet-sdk-3.0.103-linux-x64.tar.gz"
    source_sha256 = "4a2a37c0c4df9efbb22f2c00b58ac4bda95f78f6015e6fe0f1915b1ceb425ce2"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.0.103.linux-amd64-any-stack-b19ff5e1.tar.xz"
    version = "3.0.103"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "670669f5823be815cd278ec11621ce00ca671027bc6038d665516bb6b14c871b"
    source = "https://download.visualstudio.microsoft.com/download/pr/c4b503d6-2f41-4908-b634-270a0a1dcfca/c5a20e42868a48a2cd1ae27cf038044c/dotnet-sdk-3.1.101-linux-x64.tar.gz"
    source_sha256 = "a1060891482267f4b36a877b547396d7838bc36c65ef16db192344fd9b29211d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.1.101.linux-amd64-any-stack-670669f5.tar.xz"
    version = "3.1.101"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "d70d8e29262b98bc24c6fd6b625bc6e7e9b06199631e469a5171347a9168c5e4"
    source = "https://download.visualstudio.microsoft.com/download/pr/57e63f03-ebdf-4c22-96ff-2b85dc70cf7f/988576869e82a80f4a97ca5a733a5295/dotnet-sdk-3.1.102-linux-x64.tar.gz"
    source_sha256 = "e03ceeb5beaf7c228bd8dcbf7712cf12f5ccbfcd6d426afff78bfbd4524ff558"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.1.102.linux-amd64-any-stack-d70d8e29.tar.xz"
    version = "3.1.102"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.15"
    sdks = ["2.1.803"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.16"
    sdks = ["2.1.804"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.0.1"
    sdks = ["3.0.101"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.0.2"
    sdks = ["3.0.102"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.1"
    sdks = ["3.1.101"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.2"
    sdks = ["3.1.102"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
