api = "0.2"

[buildpack]
  id = "org.cloudfoundry.dotnet-core-sdk"
  name = ".NET SDK Buildpack"
  version = "{{ .Version }}"

[metadata]
  include_files = ["bin/build", "bin/detect", "buildpack.toml", "go.mod", "go.sum"]
  pre_package = "./scripts/build.sh"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "4c347c269189d3f6ff7321e505a4667f8c5fac2fcfb08a1d29f1f38d712f60c6"
    source = "https://download.visualstudio.microsoft.com/download/pr/9ba4d9b0-3fca-40ed-b5a2-1552dfa4f89e/8e5e555b543a7afd8fd764e080d25671/dotnet-sdk-2.1.804-linux-x64.tar.gz"
    source_sha256 = "51ce9fe209ed1ba5b077021fd23694808291ff8cf90dc56f04912b8cab9cb510"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.2.1.804.linux-amd64-any-stack-4c347c26.tar.xz"
    version = "2.1.804"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "20bb1ae296012d3db829cbbe5574beb2b27139546e2673b0d8414d6a8c556d2b"
    source = "https://download.visualstudio.microsoft.com/download/pr/e730fe40-e2ea-42e5-a5d0-f86830d75849/571e5a2f4ebf9f8117878eeaad5cb19b/dotnet-sdk-2.1.805-linux-x64.tar.gz"
    source_sha256 = "af5241c99f58ddf26b4b934d681750fbe5da4245d5e528eb88a6e2c78ef54cde"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk_2.1.805_linux_x64_any-stack_20bb1ae2.tar.xz"
    version = "2.1.805"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "670669f5823be815cd278ec11621ce00ca671027bc6038d665516bb6b14c871b"
    source = "https://download.visualstudio.microsoft.com/download/pr/c4b503d6-2f41-4908-b634-270a0a1dcfca/c5a20e42868a48a2cd1ae27cf038044c/dotnet-sdk-3.1.101-linux-x64.tar.gz"
    source_sha256 = "a1060891482267f4b36a877b547396d7838bc36c65ef16db192344fd9b29211d"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.1.101.linux-amd64-any-stack-670669f5.tar.xz"
    version = "3.1.101"

  [[metadata.dependencies]]
    id = "dotnet-sdk"
    sha256 = "d70d8e29262b98bc24c6fd6b625bc6e7e9b06199631e469a5171347a9168c5e4"
    source = "https://download.visualstudio.microsoft.com/download/pr/57e63f03-ebdf-4c22-96ff-2b85dc70cf7f/988576869e82a80f4a97ca5a733a5295/dotnet-sdk-3.1.102-linux-x64.tar.gz"
    source_sha256 = "e03ceeb5beaf7c228bd8dcbf7712cf12f5ccbfcd6d426afff78bfbd4524ff558"
    stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]
    uri = "https://buildpacks.cloudfoundry.org/dependencies/dotnet-sdk/dotnet-sdk.3.1.102.linux-amd64-any-stack-d70d8e29.tar.xz"
    version = "3.1.102"

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.16"
    sdks = ["2.1.804"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "2.1.17"
    sdks = ["2.1.805"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.1"
    sdks = ["3.1.101"]

  [[metadata.runtime-to-sdks]]
    runtime-version = "3.1.2"
    sdks = ["3.1.102"]

[[stacks]]
  id = "org.cloudfoundry.stacks.cflinuxfs3"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
